api:
  v1: "https://wyapi-1.toubiec.cn/api/music"
  v2: "https://wyapi-2.toubiec.cn/api/music"
  info: "/detail"
  album: "/album"
  list: "/playlist"
  lyric: "/lyric"
  durl: "/url"

opt:
  api: "v1"

  # standard: 标准音质, exhigh: 极高音质, lossless: 无损音质 hires: Hi-Res音质,
  # jyeffect: 高清环绕声, sky: 沉浸环绕声, jymaster: 超清母带
  level: "lossless"

  # hard(内嵌), ext(外挂)
  lyric: "hard"
